repository_name: samloh84/nodejs
base_repositories:
  - samloh84/centos
  - samloh84/alpine
#  - samloh84/debian
#  - samloh84/ubuntu

version_constraints:
  - '>=4.0.0'

templates:
  - Dockerfile
  - Makefile

starting_url: https://nodejs.org/dist/
scraper_url_patterns:
  - https://nodejs.org/dist/$
  - https://nodejs.org/dist/v(\d+\.\d+\.\d+)/$
version_url_patterns:
  - https://nodejs.org/dist/v(\d+\.\d+\.\d+)/$
file_patterns:
  source:
    .tar.gz: v(\d+\.\d+\.\d+)/(node-v(?:\d+\.\d+\.\d+)(\.tar\.gz))$
    .tar.xz: v(\d+\.\d+\.\d+)/(node-v(?:\d+\.\d+\.\d+)(\.tar\.xz))$
  binaries:
    .tar.gz: v(\d+\.\d+\.\d+)/(node-v(?:\d+\.\d+\.\d+)-(.+)(\.tar\.gz))$
    .tar.xz: v(\d+\.\d+\.\d+)/(node-v(?:\d+\.\d+\.\d+)-(.+)(\.tar\.xz))$
  checksums:
    sha256:
      pattern: v(\d+\.\d+\.\d+)/(SHASUMS256(\.txt))$
      signature: v(\d+\.\d+\.\d+)/(SHASUMS256(\.txt\.sig))$
    signed_sha256: v(\d+\.\d+\.\d+)/(SHASUMS256(\.txt\.asc))$
